# RAG Pipeline - Response Verifier
"""
Post-Hoc Verification (Fact-Checking) Module.

This module acts as an independent 'skeptical fact-checker' that takes a
draft response and cross-references every factual claim against the original
retrieved documents using Natural Language Inference (NLI).

Above-and-beyond enhancements over basic NLI:
  1. Claim-level citation mapping — links each claim to the specific source
  2. Assumption extraction — surfaces implicit legal assumptions
  3. Confidence calibration — grounding score 0.0-1.0, not just binary
  4. Adversarial persona — reduces self-verification bias by using a
     "devil's advocate" prompt that actively tries to find holes
"""

import sys
import json
import logging
from pathlib import Path
from typing import List, Dict, Any, Optional
from dataclasses import dataclass, field, asdict

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from rag_pipeline.embeddings import GeminiChat

logger = logging.getLogger(__name__)


# =====================
# Data Classes
# =====================

@dataclass
class ClaimVerification:
    """Verification result for a single claim extracted from the answer."""
    claim: str
    is_supported: bool
    confidence: float  # 0.0 to 1.0
    supporting_source: Optional[str] = None  # Citation of the source that supports it
    explanation: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class AssumptionCheck:
    """An implicit assumption extracted from the reasoning and its validity."""
    assumption: str
    is_valid: bool
    risk_level: str  # "low", "medium", "high"
    explanation: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class VerificationResult:
    """Full verification report for a RAG response."""
    is_grounded: bool
    grounding_score: float  # 0.0 to 1.0 calibrated confidence
    claims: List[ClaimVerification] = field(default_factory=list)
    assumptions: List[AssumptionCheck] = field(default_factory=list)
    unsupported_claims: List[str] = field(default_factory=list)
    risky_assumptions: List[str] = field(default_factory=list)
    corrected_answer: Optional[str] = None
    analysis: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "is_grounded": self.is_grounded,
            "grounding_score": round(self.grounding_score, 3),
            "claims": [c.to_dict() for c in self.claims],
            "assumptions": [a.to_dict() for a in self.assumptions],
            "unsupported_claims": self.unsupported_claims,
            "risky_assumptions": self.risky_assumptions,
            "corrected_answer": self.corrected_answer,
            "analysis": self.analysis,
        }


# =====================
# Core Verifier
# =====================

class ResponseVerifier:
    """
    Independent fact-checker for RAG responses.

    Uses LLM as an NLI (Natural Language Inference) engine with an
    adversarial "devil's advocate" persona to check entailment between
    the generated answer and the source texts.

    Why adversarial? Using the same LLM to generate AND verify creates
    self-verification bias (the model tends to agree with itself).
    By adopting a hostile, skeptical persona at zero temperature, we
    significantly reduce this bias.
    """

    def __init__(self, chat: Optional[GeminiChat] = None):
        self.chat = chat or GeminiChat()
        logger.info(f"ResponseVerifier initialized with chat key_manager: {self.chat.key_manager.key_count if self.chat.key_manager else 'default'} keys")

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def verify_grounding(
        self,
        answer: str,
        sources: List[Dict[str, Any]],
        generate_correction: bool = True,
    ) -> VerificationResult:
        """
        Verify that an answer is strictly supported by the provided sources.

        Args:
            answer: The draft response generated by the LLM
            sources: List of source documents retrieved from Pinecone/Graph
            generate_correction: If True, rewrite unsupported claims

        Returns:
            VerificationResult with per-claim scores and assumption checks
        """
        source_texts = self._format_sources(sources)

        # Step 1: Claim-level grounding check with citation mapping
        claims = self._check_claims(answer, source_texts)

        # Step 2: Assumption extraction and validation
        assumptions = self._check_assumptions(answer, source_texts)

        # Step 3: Calculate calibrated grounding score
        if claims:
            supported_count = sum(1 for c in claims if c.is_supported)
            grounding_score = supported_count / len(claims)
        else:
            grounding_score = 1.0  # No claims to check = vacuously grounded

        unsupported = [c.claim for c in claims if not c.is_supported]
        risky = [a.assumption for a in assumptions if a.risk_level in ("medium", "high")]

        is_grounded = grounding_score >= 0.8 and len(risky) == 0

        # Step 4: Generate corrected answer if needed
        corrected = None
        if not is_grounded and generate_correction and unsupported:
            corrected = self._generate_correction(answer, unsupported, source_texts)

        return VerificationResult(
            is_grounded=is_grounded,
            grounding_score=grounding_score,
            claims=claims,
            assumptions=assumptions,
            unsupported_claims=unsupported,
            risky_assumptions=risky,
            corrected_answer=corrected,
            analysis=self._summarize(claims, assumptions, grounding_score),
        )

    def verify_assumption(
        self,
        assumption: str,
        sources: List[Dict[str, Any]],
    ) -> AssumptionCheck:
        """
        Standalone method to verify a single legal assumption against sources.

        Useful when a user or the MCTS agent wants to quickly check:
        "Is it actually true that X applies in this jurisdiction?"
        """
        source_texts = self._format_sources(sources)

        prompt = f"""You are a skeptical legal auditor. Your job is to determine
whether the following ASSUMPTION is valid based ONLY on the provided legal sources.

ASSUMPTION: {assumption}

LEGAL SOURCES:
{source_texts}

Evaluate strictly. Output JSON:
{{
    "assumption": "<the assumption>",
    "is_valid": <boolean>,
    "risk_level": "<low|medium|high>",
    "explanation": "<why it is or isn't supported>"
}}

Respond with ONLY the JSON object."""

        try:
            raw = self.chat.generate(prompt, temperature=0.0, max_tokens=512)
            data = self._parse_json(raw)
            return AssumptionCheck(
                assumption=data.get("assumption", assumption),
                is_valid=bool(data.get("is_valid", False)),
                risk_level=data.get("risk_level", "high"),
                explanation=data.get("explanation", ""),
            )
        except Exception as e:
            logger.error(f"Assumption verification failed: {e}")
            return AssumptionCheck(
                assumption=assumption,
                is_valid=False,
                risk_level="high",
                explanation=f"Verification error: {e}",
            )

    # ------------------------------------------------------------------
    # Private Methods
    # ------------------------------------------------------------------

    def _format_sources(self, sources: List[Dict[str, Any]]) -> str:
        """Format source documents into a readable block for prompting."""
        parts = []
        for i, src in enumerate(sources):
            content = src.get("excerpt", src.get("content", ""))
            citation = src.get("citation", src.get("case_name", f"Source {i + 1}"))
            parts.append(f"--- [SOURCE {i + 1}: {citation}] ---\n{content}")
        return "\n\n".join(parts) if parts else "[No sources provided]"

    def _check_claims(
        self, answer: str, source_texts: str
    ) -> List[ClaimVerification]:
        """
        Decompose the answer into atomic claims and verify each one
        against the source documents with citation mapping.

        Uses an adversarial 'devil's advocate' persona to reduce
        self-verification bias.
        """
        prompt = f"""You are the DEVIL'S ADVOCATE — a ruthless, skeptical legal auditor
whose sole purpose is to FIND ERRORS. You are inherently hostile toward the Draft Answer.
Assume the answer is wrong until proven otherwise by the sources.

SOURCE DOCUMENTS (ground truth):
{source_texts}

DRAFT ANSWER (to be audited):
{answer}

INSTRUCTIONS:
1. Break the Draft Answer into individual atomic factual claims.
2. For EACH claim, determine if it is EXPLICITLY supported by the source documents.
3. A claim is "supported" ONLY if the sources directly state or logically entail it.
4. General knowledge, common sense, or inferences beyond the sources = UNSUPPORTED.
5. For supported claims, cite the specific source number (e.g., "Source 1").

Output a JSON array of claim objects:
[
    {{
        "claim": "<the atomic claim>",
        "is_supported": <boolean>,
        "confidence": <float 0.0 to 1.0>,
        "supporting_source": "<Source N or null if unsupported>",
        "explanation": "<brief reason>"
    }}
]

Respond with ONLY the JSON array."""

        try:
            raw = self.chat.generate(prompt, temperature=0.0, max_tokens=2048)
            data = self._parse_json(raw)

            if not isinstance(data, list):
                data = [data]

            return [
                ClaimVerification(
                    claim=item.get("claim", ""),
                    is_supported=bool(item.get("is_supported", False)),
                    confidence=float(item.get("confidence", 0.0)),
                    supporting_source=item.get("supporting_source"),
                    explanation=item.get("explanation", ""),
                )
                for item in data
                if item.get("claim")
            ]
        except Exception as e:
            logger.error(f"Claim verification failed: {e}")
            return []

    def _check_assumptions(
        self, answer: str, source_texts: str
    ) -> List[AssumptionCheck]:
        """
        Extract IMPLICIT legal assumptions from the answer and validate them.

        This is the key 're-verification' step the user asked for.
        Example: if the answer says "the Sagaz test applies here", the
        implicit assumption is that Canadian federal law governs the case.
        This method surfaces and validates such assumptions.
        """
        prompt = f"""You are a meticulous legal auditor. Read the following Draft Answer
and identify any IMPLICIT ASSUMPTIONS — things the answer takes for granted
without explicitly verifying them.

DRAFT ANSWER:
{answer}

SOURCE DOCUMENTS:
{source_texts}

For each implicit assumption, determine:
- Whether it is actually valid based on the sources
- How risky it is if it turns out to be wrong ("low", "medium", "high")

Common categories of implicit assumptions in legal AI:
- Jurisdictional assumptions (e.g., assuming Canadian law applies)
- Temporal assumptions (e.g., assuming current law, not historical)
- Factual assumptions (e.g., assuming a relationship is ongoing)
- Precedent assumptions (e.g., assuming a case is still good law)

Output a JSON array:
[
    {{
        "assumption": "<the implicit assumption>",
        "is_valid": <boolean>,
        "risk_level": "<low|medium|high>",
        "explanation": "<why>"
    }}
]

If no implicit assumptions are found, return an empty array: []
Respond with ONLY the JSON array."""

        try:
            raw = self.chat.generate(prompt, temperature=0.0, max_tokens=1024)
            data = self._parse_json(raw)

            if not isinstance(data, list):
                return []

            return [
                AssumptionCheck(
                    assumption=item.get("assumption", ""),
                    is_valid=bool(item.get("is_valid", True)),
                    risk_level=item.get("risk_level", "low"),
                    explanation=item.get("explanation", ""),
                )
                for item in data
                if item.get("assumption")
            ]
        except Exception as e:
            logger.error(f"Assumption extraction failed: {e}")
            return []

    def _generate_correction(
        self, answer: str, unsupported_claims: List[str], source_texts: str
    ) -> str:
        """Generate a corrected answer that removes unsupported claims."""
        claims_str = "\n".join(f"- {c}" for c in unsupported_claims)

        prompt = f"""You are a careful legal editor. The following Draft Answer
contains claims that are NOT supported by the source documents.

DRAFT ANSWER:
{answer}

UNSUPPORTED CLAIMS:
{claims_str}

SOURCE DOCUMENTS:
{source_texts}

Rewrite the answer so that:
1. All unsupported claims are removed or replaced with hedged language
   (e.g., "It is unclear whether..." or "The sources do not address...")
2. All supported claims remain intact
3. The overall structure and tone is preserved

Output ONLY the corrected answer text."""

        try:
            return self.chat.generate(prompt, temperature=0.0, max_tokens=1024)
        except Exception as e:
            logger.error(f"Correction generation failed: {e}")
            return None

    def _summarize(
        self,
        claims: List[ClaimVerification],
        assumptions: List[AssumptionCheck],
        score: float,
    ) -> str:
        """Generate a human-readable summary of the verification."""
        total = len(claims)
        supported = sum(1 for c in claims if c.is_supported)
        risky = sum(1 for a in assumptions if a.risk_level in ("medium", "high"))

        parts = [f"Grounding score: {score:.0%} ({supported}/{total} claims supported)."]
        if risky:
            parts.append(f"⚠️ {risky} risky assumption(s) detected.")
        if score >= 0.8 and risky == 0:
            parts.append("✅ Answer is well-grounded in the source documents.")
        elif score >= 0.5:
            parts.append("⚡ Answer is partially grounded. Some claims need verification.")
        else:
            parts.append("❌ Answer has significant grounding issues.")

        return " ".join(parts)

    def _parse_json(self, raw: str) -> Any:
        """Parse JSON from LLM output, handling markdown fences."""
        cleaned = raw.strip()
        if cleaned.startswith("```"):
            cleaned = cleaned.split("\n", 1)[1]
            if cleaned.endswith("```"):
                cleaned = cleaned[:-3]
            cleaned = cleaned.strip()
        return json.loads(cleaned)


if __name__ == "__main__":
    # Quick demo
    verifier = ResponseVerifier()

    test_sources = [
        {
            "citation": "Sagaz v. 671122 Ontario, [2001] 2 SCR 983",
            "excerpt": (
                "The central question is whether the person who has been "
                "engaged to perform the services is performing them as a "
                "person in business on his own account. Factors include "
                "control, ownership of tools, chance of profit, and risk of loss."
            ),
        }
    ]

    test_answer = (
        "The Sagaz test asks whether the person is in business on his own account. "
        "The Supreme Court also mandated a strict 5-part checklist that must be "
        "passed in exact order, and the test only applies in Ontario."
    )

    print("Testing verification on a partially hallucinated answer...\n")
    result = verifier.verify_grounding(test_answer, test_sources)
    print(json.dumps(result.to_dict(), indent=2))
